server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tvb.c1ec6awas4l6.us-east-2.rds.amazonaws.com:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootroot

front:
  redirect:
    url: https://www.gravifox.com
    login-url: https://www.gravifox.com/login

backend:
  upload:
    path: /var/app/current/upload/
  base:
    url: https://api.gravifox.com/

ai:
  base:
    url: http://117.17.149.66:8000
